### PR TITLE
Customer review page

### PR DESCRIPTION
**Pull request by Ha3a**
Prototype for customer review page, questions taken from questions_data.json and submit is printed to console

WORK REQUIRED 
DB: questions and answers
BACKEND: getGroup without user logged in, secret link
SERVICES

### CODE REVIEW

**Comment by Ha3a** [comment]
REQUIRES NEW BACKEND TO RUN
https://github.com/ohtuprojekti-ilmo/ohtuilmo-backend/tree/customer-review

Customer review now works through the secret link 
example "http://localhost:3000/customer-review/aprYhSEO0Hvnl9W8A"
The end of the link is the secret id from topics tables secretId

Front now fetches group name, group id, configuration id and review questions from backend.
Group name, group id, configuration id are stored in the reducer and used from there

Answers are now also saved to the database

**Comment by akiutoslahti** [comment]
Is this WIP or is it not?? 
Also, this need rebasing.

**Comment by Ha3a** [comment]
@akiutoslahti was about to exit wip status but a new feature was chosen for the branch

**Comment by akiutoslahti** [comment]
Is this now truly fit for review? If so I will review could review it tomorrow.

**Pull request merged**
